{{- $values := index .Values "benePortalAPI" -}}
{{- $global := .Values.global -}}
{{- if $values.istio.enabled  }}
{{- if $values.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" $ }}-bene-portal-api
  labels:
    {{- include "beneportal.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml $values.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if $values.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ default $values.benePortalHostname $values.istio.gateway.host | quote }}
    {{- if $values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if $values.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ default $values.benePortalHostname $values.istio.gateway.host | quote }}
    tls:
      {{- toYaml (omit $values.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
